### ISSUE TITLE
when viewing render from certain angles with tube rendering disabled, some lines don't show until the camera is moved

### ISSUE THREAD

**Issue by L10nhunter** [remcoder/gcode-preview#264] opened 2024-12-19 18:53 UTC
steps to reproduce:

1. Make sure the the model has straight lines at multiple angles.
2. insure that tube rendering is disabled. 
3. my settings for the WebGLPreview:
`{
    extrusionColor: '#7561A9;
    backgroundColor: 'black',
    buildVolume: { x: 250, y: 210, z: 220 },
    travelColor: 'limegreen',
    lineWidth: 0.8,
    lineHeight: 0.4,
    extrusionWidth: 0.8,
    renderExtrusion: true,
    renderTravel: false,
    renderTubes: false,
    initialCameraPosition: [-200, 232, 200],
}`

5. once rendered, zoom in and watch lines appear and disappear.

**Comment by remcoder** [comment] 2024-12-27 10:20
@L10nhunter I can only reproduce this when I set `lineWidth` to < 0.5 or when I disable compensation for _devicePixelRatio_. I'm on a Mac btw and using Brave atm. 

Either way, the lineWidth for line rendering is not intended to go below 1. A lineWidth of 1 means a width of 1 pixel here. So it is different from the extrusionWidth for tubes which is in mm. 

I'm closing this as it isn't a bug. It's just how Threejs renders lines. Feel free to discuss further or re-open if this is in fact a bug.

**Closed as completed** 2024-12-27 10:21 UTC
